//
// Created by Terry on 2020/4/3.
//

#ifndef ANDROIDTRAININGRECORDER_DECODE_STATE_H
#define ANDROIDTRAININGRECORDER_DECODE_STATE_H

enum DecodeState {
    STOP,
    PREPARE,
    START,
    DECODING,
    PAUSE,
    FINISH
};

#endif //ANDROIDTRAININGRECORDER_DECODE_STATE_H
